SELECT
    LGL.GEOG_LOCL_COD AS LOCAL,
    MONTH(TIEM_DIA_ID) AS MES,
    COUNT(DISTINCT(FFM.SOCI_SOCI_ID)) AS SOCIOS
FROM
    MSTRDB.DWH.FT_FDLN_MOVIMIENTOS AS FFM
    INNER JOIN MSTRDB.DWH.LU_GEOG_LOCAL AS LGL ON FFM.GEOG_LOCL_ID = LGL.GEOG_LOCL_ID AND GEOG_UNNG_ID = 2
WHERE
    YEAR(TIEM_DIA_ID) = 2026
    AND FFM.FDLN_MOVT_TIPO = 'RP'
GROUP BY
    ALL
ORDER BY
    1;